#!/bin/bash
counter=1
max=25
varName="abc"
vala=$(find | grep "abc" | sed -E 's/.\/abc//g' | sort -nr | head -1)
counter=$(($counter + $vala))
max=$(($max + $vala))
while [ $counter -le $max ]
do
        touch $varName$counter
        ((counter++))
done
